### PR TITLE
Also force aarch64 to install libs into lib, not lib64

### PR DESCRIPTION
**Pull request by stbergmann**

### CODE REVIEW

**Comment by stbergmann** [comment]
bot, build

**Comment by alexlarsson** [comment]
bot, build

**Comment by alexlarsson** [comment]
It seems to still build into lib64 on aarch64:
```
 /bin/sh ./libtool   --mode=install /usr/bin/install -c   libitm.la '/usr/lib/sdk/gcc7/lib/../lib64'
libtool: install: /usr/bin/install -c .libs/libitm.so.1.0.0 /usr/lib/sdk/gcc7/lib/../lib64/libitm.so.1.0.0
```

**Comment by alexlarsson** [comment]
Yeah, because i386 has:
```
MULTILIB_OSDIRNAMES = m64=../lib64$(call if_multiarch,:x86_64-linux-gnu)
```
And aarch64 has:
```
MULTILIB_OSDIRNAMES = mabi.lp64=../lib64$(call if_multiarch,:aarch64$(AARCH_BE)-linux-gnu)
```

So, you need a separate sed, something like:
```
sed -e '/lp64=..//s/lib64/lib/' -i.orig gcc/config/aarch64/t-aarch64-linux
```

**Pull request merged**
